name: Build and Deploy Lesson Portal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Needed to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml jinja2
    
    - name: Validate lesson files
      run: |
        echo "Validating YAML files..."
        python -c "
        import yaml
        from pathlib import Path
        
        lessons_dir = Path('lessons')
        if not lessons_dir.exists():
            print('❌ No lessons directory found')
            exit(1)
            
        yaml_files = list(lessons_dir.glob('*.yml'))
        if not yaml_files:
            print('❌ No YAML files found')
            exit(1)
            
        print(f'✅ Found {len(yaml_files)} lesson files')
        
        for yaml_file in yaml_files:
            try:
                with open(yaml_file, 'r') as f:
                    yaml.safe_load(f)
                print(f'✅ {yaml_file.name} is valid')
            except Exception as e:
                print(f'❌ {yaml_file.name} is invalid: {e}')
                exit(1)
        "
    
    - name: Build site
      run: |
        echo "Building lesson portal..."
        python scripts/build_site.py
    
    - name: Deploy Site
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./site